M48
; DRILL file {KiCad (6.0.2-0)} date Monday, March 07, 2022 at 10:03:13 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-07T22:03:13-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X8.44Y-3.625
X8.44Y-3.9375
T2
X5.09Y-2.855
X5.09Y-5.41
X8.485Y-2.855
X8.485Y-5.41
T0
M30
