-d E:\Documents\FPGA\TRS-IO++PTRS-ap\impl\gwsynthesis\TRS-IO++.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst E:\Documents\FPGA\TRS-IO++PTRS-ap\src\TRS-IO++.cst
-cfg E:\Documents\FPGA\TRS-IO++PTRS-ap\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
