M48
; DRILL file {KiCad (6.0.11)} date Sat Jan 27 17:06:15 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-27T17:06:15-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1024
%
G90
G05
T1
X3.3244Y-3.4418
T2
X5.9543Y-3.4418
T3
X2.9528Y-5.315
X7.6772Y-2.4803
T0
M30
