M48
; DRILL file {KiCad (6.0.11)} date Thu May 25 19:22:26 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-25T19:22:26-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0650
%
G90
G05
T1
X3.3244Y-3.4418
T2
X5.9543Y-3.4418
T0
M30
