/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Sat Jan 19 18:37:35 2019. */

#ifndef PB_APIPROTOS_PB_H_INCLUDED
#define PB_APIPROTOS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MediaType {
    MediaType_UNKNOWN = 0,
    MediaType_DISK = 1,
    MediaType_CASSETTE = 2,
    MediaType_COMMAND = 3,
    MediaType_BASIC = 4
} MediaType;
#define _MediaType_MIN MediaType_UNKNOWN
#define _MediaType_MAX MediaType_BASIC
#define _MediaType_ARRAYSIZE ((MediaType)(MediaType_BASIC+1))

typedef enum _Trs80Extension_Trs80Model {
    Trs80Extension_Trs80Model_UNKNOWN_MODEL = 0,
    Trs80Extension_Trs80Model_MODEL_I = 1,
    Trs80Extension_Trs80Model_MODEL_III = 2,
    Trs80Extension_Trs80Model_MODEL_4 = 3,
    Trs80Extension_Trs80Model_MODEL_4P = 4
} Trs80Extension_Trs80Model;
#define _Trs80Extension_Trs80Model_MIN Trs80Extension_Trs80Model_UNKNOWN_MODEL
#define _Trs80Extension_Trs80Model_MAX Trs80Extension_Trs80Model_MODEL_4P
#define _Trs80Extension_Trs80Model_ARRAYSIZE ((Trs80Extension_Trs80Model)(Trs80Extension_Trs80Model_MODEL_4P+1))

/* Struct definitions */
typedef struct _ApiResponseApps {
    bool success;
    char message[128];
    pb_callback_t app;
/* @@protoc_insertion_point(struct:ApiResponseApps) */
} ApiResponseApps;

typedef struct _ApiResponseMediaImages {
    bool success;
    char message[128];
    pb_callback_t mediaImage;
/* @@protoc_insertion_point(struct:ApiResponseMediaImages) */
} ApiResponseMediaImages;

typedef struct _MediaImage {
    MediaType type;
    char filename[128];
    pb_callback_t data;
    int64_t uploadTime;
    char description[128];
/* @@protoc_insertion_point(struct:MediaImage) */
} MediaImage;

typedef struct _Trs80Extension {
    Trs80Extension_Trs80Model model;
/* @@protoc_insertion_point(struct:Trs80Extension) */
} Trs80Extension;

typedef struct _App {
    char id[37];
    char name[64];
    char version[24];
    char description[1024];
    int32_t release_year;
    pb_callback_t screenshot_url;
    char author[64];
    Trs80Extension ext_trs80;
/* @@protoc_insertion_point(struct:App) */
} App;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ApiResponseApps_init_default             {0, "", {{NULL}, NULL}}
#define ApiResponseMediaImages_init_default      {0, "", {{NULL}, NULL}}
#define App_init_default                         {"", "", "", "", 0, {{NULL}, NULL}, "", Trs80Extension_init_default}
#define Trs80Extension_init_default              {_Trs80Extension_Trs80Model_MIN}
#define MediaImage_init_default                  {_MediaType_MIN, "", {{NULL}, NULL}, 0, ""}
#define ApiResponseApps_init_zero                {0, "", {{NULL}, NULL}}
#define ApiResponseMediaImages_init_zero         {0, "", {{NULL}, NULL}}
#define App_init_zero                            {"", "", "", "", 0, {{NULL}, NULL}, "", Trs80Extension_init_zero}
#define Trs80Extension_init_zero                 {_Trs80Extension_Trs80Model_MIN}
#define MediaImage_init_zero                     {_MediaType_MIN, "", {{NULL}, NULL}, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define ApiResponseApps_success_tag              1
#define ApiResponseApps_message_tag              2
#define ApiResponseApps_app_tag                  3
#define ApiResponseMediaImages_success_tag       1
#define ApiResponseMediaImages_message_tag       2
#define ApiResponseMediaImages_mediaImage_tag    3
#define MediaImage_type_tag                      1
#define MediaImage_filename_tag                  2
#define MediaImage_data_tag                      3
#define MediaImage_uploadTime_tag                4
#define MediaImage_description_tag               5
#define Trs80Extension_model_tag                 1
#define App_id_tag                               1
#define App_name_tag                             2
#define App_version_tag                          3
#define App_description_tag                      4
#define App_release_year_tag                     5
#define App_screenshot_url_tag                   6
#define App_author_tag                           7
#define App_ext_trs80_tag                        8

/* Struct field encoding specification for nanopb */
extern const pb_field_t ApiResponseApps_fields[4];
extern const pb_field_t ApiResponseMediaImages_fields[4];
extern const pb_field_t App_fields[9];
extern const pb_field_t Trs80Extension_fields[2];
extern const pb_field_t MediaImage_fields[6];

/* Maximum encoded size of messages (where known) */
/* ApiResponseApps_size depends on runtime parameters */
/* ApiResponseMediaImages_size depends on runtime parameters */
/* App_size depends on runtime parameters */
#define Trs80Extension_size                      2
/* MediaImage_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define APIPROTOS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
