-d C:\git\TRS-IO-M3\src\fpga\m3\v2.1\TRS-IO\impl\gwsynthesis\TRS-IO.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\git\TRS-IO-M3\src\fpga\m3\v2.1\TRS-IO\src\trs-io.cst
-cfg C:\git\TRS-IO-M3\src\fpga\m3\v2.1\TRS-IO\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
